### ISSUE TITLE
Kickstart the Reps Identity working group

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#12]
## Goal: 
Setup the Identity WG and have a first meeting to discuss goals, key result and next steps.

## Success:
Within the next week (counting from April 19) we held an initial, open meeting and have at least 3 next steps with owners.

## Related Issues & Links: 
-

## Roles:
Owner: @MichaelKohler 
Involved: @ioana-chiorean @ThePhoenixBird @umeshagarwal 

## Required: 
- [x] Send out doodle (@MichaelKohler, Due: April 19)
- [x] Schedule meeting (@MichaelKohler, Due: April 22)
- [x] Update working doc with key results, open questions and next steps ([needs owner], Due: April 25)

**Comment by MichaelKohler** [comment]
Sent out preliminary info and doodle at https://discourse.mozilla-community.org/t/reps-identity-comms-working-group/8174

**Comment by MichaelKohler** [comment]
We've had our first meeting yesterday, we defined our key results and next steps. The next meeting will happen the week around the 3rd May.

Working doc: https://docs.google.com/document/d/1XaVUHlAPwHhz4svumFiyJJBHP5H2TMKigdsmr5g6rfA/edit#

Discourse discussion: https://discourse.mozilla-community.org/t/reps-identity-comms-working-group/8174/7

I think we're good here for now, therefore closing this issue since the goal is achieved.

**Comment by ioana-chiorean** [comment]
🎉
