### ISSUE TITLE
Document "Outwards communication" Session from Berlin

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#18]
## Goal: 
The part from the Communication session in Berlin regarding "Outwards communication" is documented and suggestions to implement are in place.

## Related Issues & Links: 
Identity & Communications WG

## Roles:
* Owner: @ioana-chiorean 
* Involved: @MichaelKohler

## Required: 
- [ ] Document the session (@ioana-chiorean, Due: Apr 30th) 
- [ ] Come up with suggestion on what out of that to implement (..., Due: May 15th)

**Comment by Mte90** [comment]
With outwards we are talking to mozillians or for everyone?

**Comment by MichaelKohler** [comment]
> With outwards we are talking to mozillians or for everyone?

With outwards we mean everything that the public might see. This might (or might not) include Twitter, the blog, Facebook, Instagram, whatever we come up with to promote the program and give us visibility in an impactful way.

**Comment by Mte90** [comment]
I remember a case of a guy that came to a my event in Italy only because he saw that on mozilla.org, the interesting part that for him to came was means 3 hour of driving and he chosen to came only because was Mozilla and he see that there aren't events in his zone.
So I think that something about the stuff the reps do like the events needs to get more promotion by Mozilla.
We need to promote our activities because the program itself with the stuff done get auto promotion.

**Comment by Mte90** [comment]
Will be pretty cool if in about:home of Firefox there are showed all the events for the country of the user extracted from reps in that month.
I think that it is the best way for promotion without to do many complications.

**Comment by nukeador** [comment]
@couci is telling that this is now done. Please document where ;)
