### ISSUE TITLE
Create Plan for Functional Doers

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#195]
## Goal: 
We have a plan on what Functional Doers role is within Reps.

## Related Issues & Links: 
https://discourse.mozilla-community.org/t/statistics-about-reps-path-responses/16206

## Roles:

Responsible: TBD
Accountable: Reps Council
Supporting:
Consulted:
Informed: 

## Required: 
* Input from Strategy Projects
* Initial plan

**Comment by couci** [comment]
- [ ] start working on open questions on framing on what is the problem and on needs before the all-hands @Flore-mozfr 
- [ ] Ask @francjp about list of volunteers @Flore-mozfr @couci

**Comment by gaby2300** [comment]
I am a very long time QA tester (I am still at it) and an actual Functional Doer Rep. 
That's why I wonder if it would be possible to add more specific QA options to the Reps Reports site such as  "Participated in a Testday" for example, or "Tested a new Firefox Quantum feature".
Some localization items would be great too!

The above is what I do every day and would make my Reps reports much easier to create an add.

**Comment by MichaelKohler** [comment]
I'm closing this in favor of the mission driven mozillians projects.
