### ISSUE TITLE
Update Interests, Activities and Functional Areas on the portal 2019

### ISSUE THREAD

**Issue by yomanpatil** [mozilla/Reps#373]
## Goal: 
Update Interests, Activities and Functional Areas on the report system. Remove the old ones and brainstorm on adding new.

How to join? leave your thoughts in the ticket!

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible: @yomanpatil 

Accountable:

Supporting: @couci 

Consulted:

Informed: 

## Required: 
- [ ]List of things to change to check with Reps Council (owner, Due: Mar 31st)

**Comment by gaby2300** [comment]
Hello,

It would be great and very useful if the following items could be added.

I am talking about adding "Testing" or something similar to the Initiatives section. As it is now, when I join a testday, I have to select "Other" in this section. I'd much rather include it in a more specific item.

Joined a Firefox SUMO Sprint in the Activities section. As it is now, there is no way to report it!

Campaign in the Contribution area. As it is now, when I join a campaign, there is no way to report it!

Thanks!

**Comment by couci** [comment]
hey @gaby2300 thanks for the message
On testing there is one on contribution area, testing is an area where we contribute not an initiative in this point.
Sumo Days I see it now on the updated initiative section, doesn't work for you?
And campaigns is not in contribution area is because it's not an area we contribute to, things like l10n and Testing go there. Campaigns are an umbrella that's why it's under initiatives. Does it make sense or is it more confusing.

**Comment by gaby2300** [comment]
El lun., 1 de abr. de 2019 a la(s) 12:56, Konstantina Papadea (
notifications@github.com) escribió:

> hey @gaby2300 <https://github.com/gaby2300> thanks for the message
>
You are welcome!

> On testing there is one on contribution area, testing is an area where we
> contribute not an initiative in this point.
>
Right!  I understand but.... When I join a Testday I have to select "Other"
in the Initiative section. It seems very nonspecific to me. I´d much rather
a more specific item!

> Sumo Days I see it now on the updated initiative section, doesn't work for
> you?
>
Yes, I wrote this before the update, thanks!

> And campaigns is not in contribution area is because it's not an area we
> contribute to, things like l10n and Testing go there. Campaigns are an
> umbrella that's why it's under initiatives.
>
So, if I join a Support Sprint, the contribution area is User Support
(SUMO). What if I join a campaign like the Privacy one? Would it be
Community Support?

Some time ago I joined the following activity: Review Spanish sentences for
Common Voice. The activity was Participated in a campaign. The initiative,
Other. Again, not specific!

All Pontoon translations go under Other as well!

Maybe Other is another umbrella but it seems to include lots of different
activities. Couldn't we add some items to better differentiate them?


Does it make sense or is it more confusing.
>
Some of it makes perfect sense!

Thanks for "hearing" me out!

Regards,
Gabriela

**Comment by yomanpatil** [comment]
thank you for your valuable inputs @gaby2300 

We will discuss it with the council and will update you.

**Comment by couci** [comment]
> Right! I understand but.... When I join a Testday I have to select "Other" in the Initiative section. It seems very nonspecific to me. I´d much rather a more specific item! 

was that part of an initiative supported right now? was it under a campaign, or was an event organized? I am all in to create another initiative but it would make sense to put it under an initiative we are aware of otherwise we will end up having numerous initiatives that can end up be confusing

>So, if I join a Support Sprint, the contribution area is User Support (SUMO). What if I join a campaign like the Privacy one? Would it be Community Support?

I would actually say Evangelism Mission

> Some time ago I joined the following activity: Review Spanish sentences for Common Voice. The activity was Participated in a campaign. The initiative, Other. Again, not specific!

The initiative should be campaigns 

> Maybe Other is another umbrella but it seems to include lots of different activities. Couldn't we add some items to better differentiate them?

I think the initiative part is what is confusing rather the other category itself. Initiatives are what the Reps program is currently advocating for the Reps to do. That's why the focus is under campaigns, activate and inprogram contributions. Anything else doesn't fall under an initiative we are actively asking our Reps to do as part of their reps activities that's why they fall under Other. The focus here is not to over-complicate our reporting system and create for everything rather than simplifying and help people focus on those initiatives. Of course things like pontoon translation is important but right now we don't have an active campaign or initiative prompting our Reps to it. That's why it fall under other

**Comment by gaby2300** [comment]
All right Konstantina, I understand!

Thanks for such a detailed answer!

Best regards,
Gabriela
