### ISSUE TITLE
Council Elections - H2 2019

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#389]
## Goal:
Hold the Council elections in order to occupy the spots that are free after the term of one year is ending for:

🎓 Monica
🎓 Yofie
🎓 Yuliana

We have 3 open spots.

## Success:
The elections take place and we have 3 Council members

## Related Issues & Links:
- Previous Elections #15, #114, #208, #284, #327, #366 
 
## Roles:
Owner: @ioana-chiorean 
Involved: @couci, Reps Peers
Supporting: @prathameshchavan 
Informed: @nukeador, Reps

## Required:
(format of the dates is DD.MM.YYYY)

### Planning
- [x] 11.09.2019 - Plan Town Halls (@MichaelKohler)
- [x] 19.09.2019 - Timeline presentation and announcement in Reps Call / Discourse / Mailing list (@ioana-chiorean)

### Nomination & Campaigning
- [x] 23.09.2019 - Call for Nominees starts (1 week) (@ioana-chiorean)
- [x] 23.09.2019 - Share invitation for candidating on Mailing List (@ioana-chiorean)
- [x] 23.09.2019 - Share invitation for candidating on Telegram (@ioana-chiorean)
- [x] 29.09.2019 - Call for Nominees closes (@ioana-chiorean)
- [x] 30.09.2019 - CPG check (@ioana-chiorean)
- [x] 30.09.2019 - Q&A starts on Discourse (1 week) (@ioana-chiorean)
- [x] 01.10.2019 - Nominees Q&A Town Hall Timezone 1 (@ioana-chiorean)
- [x] 03.10.2019 - Nominees Q&A Town Hall Timezone 2 (@ioana-chiorean)
- [x] 06.10.2019 - Deadline for answers in Discourse Q&A (@ioana-chiorean)

### Voting
- [x] 07.10.2019 - Voting starts (1 week) (@ioana-chiorean)
- [x] 07.10.2019 - Tweet about voting (@MichaelKohler)
- [x] 14.10.2019 - Voting closes (@ioana-chiorean)
- [x] 15.10.2019 - Voting results published (@ioana-chiorean)
- [x] 15.10.2019 - Voting Analysis is published (@MichaelKohler)
- [x] 15.10.2019 - Wiki Pages are updated (@MichaelKohler)

### Onboarding
- [x] 15.10.2019 - Onboarding begins - Schedule meeting with new Council members (@couci)
- [ ] TBD - Call with Nominees & Peers to make sure they understand accountability (@anknite )
- [x] 18.10.2019 - New Council members have write access to GitHub Reps repo (@MichaelKohler)
- [x] 23.10.2019 - New Council members are in the OI Mozillians group (@couci)
- [x] 23.10.2019 - New Council members are in the Council Mozillians group (@couci)
- [x] 23.10.2019 - New Council members are in the Telegram group (@couci)
- [x] 23.10.2019 - New Council members are in the reps-council alias (@couci)
- [x] 23.10.2019 - New Council members have access to Slack / #oi-team channel (@couci)
- [x] 04.11.2019 - Onboarding is done and new Council is operational - new Council members have confirmed they all have access to everything (@couci)
- [ ] 04.11.2019 - Old Council members are removed from Telegram group (@couci)
- [x] 04.11.2019 - Old Council members are removed from OI Mozillians group (@couci)
- [x] 04.11.2019 - Old Council members are removed from Council Mozillians group (@couci)
- [ ] 04.11.2019 - Old Council members are removed from Reps GitHub collaborators (@MichaelKohler)
- [x] 04.11.2019 - Reps Portal is updated with new Council members in Council group (@couci)
- [ ] 04.11.2019 - Blog announcement for new members + outgoing members is published (@couci)
- [x] 04.11.2019 - Mozilla Leadership Page is updated (@MichaelKohler)

## Updates required:
- [x] Create [15th entry](https://wiki.mozilla.org/ReMo/Council/History)

## Dependencies:
- [x] Verify if there are any regional holidays/festivities during the election period
- [x] Get general feedback from Reps

**Comment by MichaelKohler** [comment]
Town Hall "Reserve the date": https://discourse.mozilla.org/t/council-elections-fall-2019-reserve-date-for-town-halls/44877/2

**Comment by ioana-chiorean** [comment]
Reps portal event: https://reps.mozilla.org/e/reps-council-elections-h2-2019-nominees/ 
Announcement elections: https://discourse.mozilla.org/t/important-council-elections-h2-2019-please-read/45716

**Comment by ioana-chiorean** [comment]
Nominee from the event: https://reps.mozilla.org/e/reps-council-elections-h2-2019-nominees/ 

Verified:
https://reps.mozilla.org/u/shahbaz/
https://reps.mozilla.org/u/felipez3r0/
https://reps.mozilla.org/u/balapandu222/
https://reps.mozilla.org/u/bhuvanameenakshi/
https://reps.mozilla.org/u/lasr21/

Not eligible:
https://reps.mozilla.org/u/Liv/
https://reps.mozilla.org/u/smsnobin77/
https://reps.mozilla.org/u/ranjithraj/

**Comment by ioana-chiorean** [comment]
Here is the tracking list:
* [Bala Subramaniyan](https://reps.mozilla.org/u/balapandu222/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-h2-2019-nominee-q-a/46004/4) 
  - [ ] Video (optional)
  - [ ] Townhall 1 (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life)
* [Bhuvana Meenakshi Koteeswaran](https://reps.mozilla.org/u/bhuvanameenakshi/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-h2-2019-nominee-q-a/46004/5) 
  - [x] [Video](https://youtu.be/WjGr5HJM0fc)
  - [ ] Townhall 1 (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life)
* [Felipe Do Espirito Santo](https://reps.mozilla.org/u/felipez3r0/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-h2-2019-nominee-q-a/46004/2) 
  - [ ] Video (optional)
  - [ ] Townhall 1 (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life)
* [Luis A Sanchez](https://reps.mozilla.org/u/lasr21/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-h2-2019-nominee-q-a/46004/6) 
  - [x] [Video](https://www.youtube.com/watch?v=3-SzG1uIgig)
  - [ ] Townhall 1 (preferred, but optional due to timezones/personal life)
  - [ ] Townhall 2 (preferred, but optional due to timezones/personal life)
* [Md Shahbaz Alam](https://reps.mozilla.org/u/shahbaz/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-h2-2019-nominee-q-a/46004/3) 
  - [x] [Video](https://youtu.be/ejicLMiJPAY)
  - [x] Townhall 1 (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life) (joined for the last 10 minutes)

**Comment by ioana-chiorean** [comment]
Voting is here: https://reps.mozilla.org/v/reps-council-elections-h2-2019-3-spots/ 
Discussions and answers: https://discourse.mozilla.org/t/important-council-elections-h2-2019-nominee-q-a/46004

**Comment by MichaelKohler** [comment]
And here's the analysis: https://michaelkohler.github.io/reps-voting-analysis/#/ :)

**Comment by ioana-chiorean** [comment]
Council entry made by MK - https://wiki.mozilla.org/Reps/Council/History#15th_Council_-_.28October_2019.29
Discourse - https://discourse.mozilla.org/t/important-council-elections-h2-2019-results-and-next-steps/46850

**Comment by MichaelKohler** [comment]
https://www.mozilla.org/en-US/about/leadership/#reps-council is updated
