### ISSUE TITLE
Faster Onboarding for New Reps

### ISSUE THREAD

**Issue by brianking** [mozilla/Reps#94]
The new Reps queue is continuously blocked by lack of human screening/onboarding/mentoring time. We should consider ways to bypass this:

Some possible things to try:
- Council screens people
- Create onboarding Webinar
- Better enforce 3 month onboarding before becoming a "real Rep"

**Comment by MichaelKohler** [comment]
We are currently testing this, we will write a Discourse topic or blog post about this once we have more info. Our next step is to invite applicants to a onboarding Webinar and create the content for this.

**Comment by MichaelKohler** [comment]
Since we have #101 to test a webinar, I'm putting this to blocked until we have completed our Q1 goal of identifying common shared onboading processes with other parts of the org. Until then we will also have an idea whether the webinar works. With both of these projects as input, we can evaluate here how we could move faster.

**Comment by MichaelKohler** [comment]
Filed https://github.com/mozilla/Reps/issues/154 and https://github.com/mozilla/Reps/issues/155 to go further here.
